

Looter.items = {
  "1981b4af04434077afafc78691056387": {
    name: "WaylandsBoots",
    displayName: "Wayland's Boots",
    details: "Break spikes, take names",
    rarity: rarity.common,
    type: type.relic,
    cost: 8,
    craftingCost: 375,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "25a2fe2d57a34b6598d34cbbb58fdeb0": {
    name: "Galoshes",
    displayName: "Galoshes",
    details: "Walk and jump on oil and poison",
    rarity: rarity.common,
    type: type.relic,
    cost: 275,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "d2b0fec2b4cf44e8aa63b0aa94441fd5": {
    name: "FloatBoots",
    displayName: "Float Boots",
    details: "Walk on air",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 26,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "7ee59f418896447ca03ce09665771ae6": {
    name: "LavaWalkers",
    displayName: "Lava Walkers",
    details: "Walk on fire",
    rarity: rarity.common,
    type: type.relic,
    cost: 275,
    craftingCost: 26,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "a7ae4ce21346402ca6fe2ad0c09b1c14": {
    name: "HeliosBoots",
    displayName: "Helios Boots",
    details: "Fire patches last for much longer and deal more damage",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 550,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "23f1ec241ee449419dfcf3db6ede4f8a": {
    name: "HeavyBoots",
    displayName: "Heavy Boots",
    details: "Jump again in midair to land with authority",
    rarity: rarity.common,
    type: type.relic,
    cost: 275,
    craftingCost: 22,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "fe3880cccffb46a6ba510453822df02b": {
    name: "ButchersCleaver",
    displayName: "Butcher's Cleaver",
    details: "Sometimes drop meat from your enemies",
    rarity: rarity.common,
    type: type.relic,
    cost: 525,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "637c8bf20a8d4e6da5bcd6bbbac68f12": {
    name: "Key Blade",
    displayName: "Key Blade",
    details: "Increases swing damage for each key you have",
    rarity: rarity.common,
    type: type.relic,
    cost: 375,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "9919d2d2d31941f2a96f898d56e8d297": {
    name: "LegendaryBlade",
    displayName: "Master Pickaxe",
    details: "Fire projectiles at full health",
    rarity: rarity.rare,
    type: type.relic,
    cost: 600,
    craftingCost: 50,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "49e257bc3ed04cde9e5b0a7089d7af10": {
    name: "Mjolnir",
    displayName: "Mjölnir",
    details: "Thrown pickaxe summons lightning on hit",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 850,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "212720105e1a4605b4d5bc4295a684cd": {
    name: "DoomBlade",
    displayName: "Doom Blade",
    details: "Gain damage for each carried curse",
    rarity: rarity.common,
    type: type.relic,
    cost: 1000,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2d5d75f5824242b781e8295d5f25b996": {
    name: "BattleAxe",
    displayName: "Battle Axe",
    details: "Increases swing size, but slightly decreases swing damage",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 26,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2e1f6f7792eb4409a359778402737ed1": {
    name: "Glaive",
    displayName: "Glaive",
    details: "Increases throw size.",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 26,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2f9b6e005bf64057936c3101264f812e": {
    name: "Javelin",
    displayName: "Javelin",
    details: "Damage of a thrown pickaxe increases as it travels further",
    rarity: rarity.common,
    type: type.relic,
    cost: 475,
    craftingCost: 35,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "05ad55b489ff4af28e34ab471ecd0640": {
    name: "Masa",
    displayName: "Masa",
    details: "Reduces throw damage and increases swing damage",
    rarity: rarity.rare,
    type: type.relic,
    cost: 410,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "78d8214111974925b1e2039f20b728cf": {
    name: "Mune",
    displayName: "Mune",
    details: "Reduces swing damage and increases throw damage",
    rarity: rarity.rare,
    type: type.relic,
    cost: 1,
    craftingCost: 490,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "c5791c753f7e42de8a2814bd4b17504a": {
    name: "Masamune",
    displayName: "Masamune",
    details: "Instantly kills enemies sometimes",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 900,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "f568bbf4ecb54daf9d7d472f06d97521": {
    name: "Suneater",
    displayName: "Suneater",
    details: "Consumes all current and future blessings and converts them to swing damage",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 900,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "e161e4e3083948eaa22f9830394b1235": {
    name: "VorpalBlade",
    displayName: "Vorpal Blade",
    details: "Attack quickly without stopping",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 50,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "66b7f22d45354e549d2a4a18ce9792f7": {
    name: "Twisted Blade",
    displayName: "Twisted Blade",
    details: "Increases critical strike chance for each carried curse",
    rarity: rarity.common,
    type: type.relic,
    cost: 375,
    craftingCost: 30,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2945df6b2ea043dd94c67ba09aefbe2b": {
    name: "ObsidianKnife",
    displayName: "Obsidian Knife",
    details: "Dramatically increases damage, but breaks when hit.",
    rarity: rarity.rare,
    type: type.relic,
    cost: 650,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "54d1936d55494194a42d56c6f314c763": {
    name: "DirksHammer",
    displayName: "Dirk's Hammer",
    details: "Transmute an item by hitting it",
    rarity: rarity.rare,
    type: type.relic,
    cost: 500,
    craftingCost: 50,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "e6472b78a0d74240bbdd5e5dbc54c350": {
    name: "GoldenAxe",
    displayName: "Golden Axe",
    details: "Spent gold is turned into bonus damage",
    rarity: rarity.rare,
    type: type.relic,
    cost: 700,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "51be11a14af842569bf13dd47d53fd84": {
    name: "TwinAxe",
    displayName: "Twin Axe",
    details: "Gain a second pickaxe",
    rarity: rarity.rare,
    type: type.relic,
    cost: 725,
    craftingCost: 65,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "a8d3215241a94555866450ab791bc7e3": {
    name: "Resurrection",
    displayName: "Resurrection",
    details: "Resurrect on death",
    rarity: rarity.rare,
    type: type.relic,
    cost: 1200,
    craftingCost: 46,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "623c929400f44c05b07827fef3426e60": {
    name: "GordonsTunic",
    displayName: "Gordon's Tunic",
    details: "Reduces elemental damage",
    rarity: rarity.common,
    type: type.relic,
    cost: 280,
    craftingCost: 14,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "b367a2746211405a8dda8d560f88b6d3": {
    name: "Breastplate",
    displayName: "Breastplate",
    details: "",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 55,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "53f62e71c29143f79a27abca6069f52b": {
    name: "Pauldron",
    displayName: "Pauldron",
    details: "Adds a point of armor to the health bar",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2f342d2da24340b383d49f1fb9374e5a": {
    name: "Gauntlets",
    displayName: "Gauntlets",
    details: "Adds a point of armor to the health bar",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 35,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "e930152d55884ffbb8a0ce9edd6a46f1": {
    name: "Greaves",
    displayName: "Greaves",
    details: "Adds a point of armor to the health bar",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "19dc5130b5404db7a09262d609d9b8ba": {
    name: "ShieldofQuills",
    displayName: "Shield of Quills",
    details: "Gain two points of armor, armor increases damage",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 770,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "630bd51306d34a9c9de7b041f1a3caee": {
    name: "BlastSuit",
    displayName: "Blast Suit",
    details: "Invulnerability to friendly bomb blasts and increases bomb damage",
    rarity: rarity.common,
    type: type.relic,
    cost: 275,
    craftingCost: 14,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "ca4e94bdc2cc43329474ef40230aca52": {
    name: "Pillow",
    displayName: "Hoodie's Pillow",
    details: "Reduces physical damage",
    rarity: rarity.rare,
    type: type.relic,
    cost: 350,
    craftingCost: 22,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "a1ca0abb4f8c47bbb719be48fb7fd470": {
    name: "SoulGuard",
    displayName: "Soul Guard",
    details: "Reduces and redirects damage to your max HP",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 850,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "a4186f3d71cb4706b4884f6efcf186dc": {
    name: "TangleGuard",
    displayName: "Tortoise Shield",
    details: "Slows enemy projectiles",
    rarity: rarity.common,
    type: type.relic,
    cost: 375,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2a64aa4851c94841ae297322646e6bdc": {
    name: "WetBlanket",
    displayName: "Wet Blanket",
    details: "Puts out fires immediately, but requires water charges",
    rarity: rarity.common,
    type: type.relic,
    cost: 275,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "95c9369deaba40caa44b1b48989a6a17": {
    name: "WarPaint",
    displayName: "War Paint",
    details: "Increase attack damage and speed when killing enemies",
    rarity: rarity.common,
    type: type.relic,
    cost: 480,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "fd702e9d2662490f886876ee598b15d7": {
    name: "Battlestandard",
    displayName: "Battle Standard",
    details: "Increases move, attack, and throw speed at the beginning of battle",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "6bbe9142f1144e7cac6b0f2edf13cac9": {
    name: "Catalyst",
    displayName: "Catalyst",
    details: "When healed, heal again",
    rarity: rarity.common,
    type: type.relic,
    cost: 280,
    craftingCost: 16,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "ecb92c9f921647a69fa3bcd95bb535e7": {
    name: "SeltsEgg",
    displayName: "Selt's Egg",
    details: "Spawn larvae on entrance",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 15,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "5482a1b1b71b433d886865f2394f2fcc": {
    name: "ElectrifiedOrb",
    displayName: "Electrified Orb",
    details: "Orbits the peasant and shocks enemies on contact",
    rarity: rarity.rare,
    type: type.relic,
    cost: 425,
    craftingCost: 30,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "cd5580348c4d4a3cbcba94eafc169f4a": {
    name: "OthermineConduit",
    displayName: "Othermine Conduit",
    details: "Ghastly hands will attack the enemy",
    rarity: rarity.rare,
    type: type.relic,
    cost: 480,
    craftingCost: 55,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "ca58b2a9d6cc4f56ae0699e33578a2e2": {
    name: "Doll",
    displayName: "Doll",
    details: "Blocks the next few curses.",
    rarity: rarity.common,
    type: type.relic,
    cost: 375,
    craftingCost: 22,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "d21a2fe3ce9d4fddb34a59dd4df3773f": {
    name: "Devotion",
    displayName: "Devotion",
    details: "Pray twice at altars",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 30,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "4b36bbc087004750a1526304aef7b088": {
    name: "108Beads",
    displayName: "108 Beads",
    details: "Heal when praying at an altar",
    rarity: rarity.common,
    type: type.relic,
    cost: 360,
    craftingCost: 12,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "80242154d4284cc6aab221292cb0ae93": {
    name: "HolyGuacamole",
    displayName: "Holy Guacamole",
    details: "Find more altar rooms",
    rarity: rarity.rare,
    type: type.relic,
    cost: 400,
    craftingCost: 20,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "25d89c4cdce0444bb617016d3fa547d0": {
    name: "SonicBoom",
    displayName: "Sonic Boom",
    details: "Throw really fast",
    rarity: rarity.common,
    type: type.relic,
    cost: 280,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "d8f7d033bec0417ab0b553f3a51a9a7f": {
    name: "SewingKit",
    displayName: "Sewing Kit",
    details: "Keep all your gold when you die",
    rarity: rarity.rare,
    type: type.relic,
    cost: 750,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "b29ea427f7f64aa3a06c8e19a0495648": {
    name: "SimpleChest",
    displayName: "Simple Chest",
    details: "Overstocks the shop",
    rarity: rarity.common,
    type: type.relic,
    cost: 250,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "93272a3527ad43f7a68272a0fdb560a3": {
    name: "SupplyCrate",
    displayName: "Box of Holding",
    details: "Pilfer shop items are instantly restocked",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 1500,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "074da99ced7f4993b38cb90df3a27d84": {
    name: "MealTicket",
    displayName: "Meal Ticket",
    details: "Free food at the shop, right now!",
    rarity: rarity.common,
    type: type.relic,
    cost: 300,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "6774d4be9573481f8e6fa97add614285": {
    name: "AdventurersHat",
    displayName: "Adventurer's Hat",
    details: "Discover more secret rooms",
    rarity: rarity.common,
    type: type.relic,
    cost: 250,
    craftingCost: 20,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "376feb7893994baf826df320010a2eae": {
    name: "AdventurersWhip",
    displayName: "Adventurer's Whip",
    details: "Discover more treasure rooms",
    rarity: rarity.rare,
    type: type.relic,
    cost: 475,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "bc3b600bea3d416391e2549c137fff63": {
    name: "Golden Idol",
    displayName: "Golden Idol",
    details: "Discover more rooms and get rich",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 725,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "d6045725bae4407ea8492ff1e4fa7c3f": {
    name: "TotemOfLife",
    displayName: "Totem of Life",
    details: "Sustain yourself through adventure",
    rarity: rarity.common,
    type: type.relic,
    cost: 550,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "fe3df61649f84dd2b08492c1788d92af": {
    name: "AphoticCharm",
    displayName: "Aphotic Charm",
    details: "Heal in each new room for each curse",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 18,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2380817a345d4458b5630768a38f35a1": {
    name: "DillonsClaw",
    displayName: "Dillon's Claw",
    details: "Deal even more damage when you critical strike",
    rarity: rarity.common,
    type: type.relic,
    cost: 350,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "6910c28b900043d48911f9ae27e343cf": {
    name: "ShadowsFang",
    displayName: "Shadow's Fang",
    details: "Higher chance to critical strike",
    rarity: rarity.common,
    type: type.relic,
    cost: 350,
    craftingCost: 10,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "815f242a079240b8833a32c5f408e03a": {
    name: "BladeMail",
    displayName: "Blade Mail",
    details: "Repeatedly returns damage",
    rarity: rarity.common,
    type: type.relic,
    cost: 200,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "be05dceb707e415ca9224898a15bd1d3": {
    name: "Duplicator",
    displayName: "Duplicator",
    details: "Relic rooms present a tantalizing choice",
    rarity: rarity.rare,
    type: type.relic,
    cost: 600,
    craftingCost: 26,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "87447b9566774ef486aa065a51a2bf4e": {
    name: "Hyperstone",
    displayName: "Hyperstone",
    details: "Increase attack speed",
    rarity: rarity.rare,
    type: type.relic,
    cost: 510,
    craftingCost: 45,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "262277e1e3914d1aae80a2d9f5acb3bd": {
    name: "MinersFlask",
    displayName: "Miner's Flask",
    details: "Feel the effects of a potion for longer",
    rarity: rarity.common,
    type: type.relic,
    cost: 375,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "1e47701bb3324ddfb2c097dda2506453": {
    name: "Lunchbox",
    displayName: "Lunchbox",
    details: "Store a piece of food for later",
    rarity: rarity.common,
    type: type.relic,
    cost: 380,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2725a7b0032447a98b7604d29395317a": {
    name: "Large Ember",
    displayName: "Large Ember",
    details: "Light nearby enemies on fire",
    rarity: rarity.rare,
    type: type.relic,
    cost: 400,
    craftingCost: 20,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "70965440d15240d1a7ac7c8ddff4c9b2": {
    name: "ItemPopcorn",
    displayName: "Popcorn",
    details: "Items will sometimes duplicate themselves",
    rarity: rarity.common,
    type: type.relic,
    cost: 650,
    craftingCost: 16,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "6b18a3a60fe342f1833aff1526898e11": {
    name: "GoldPopcorn",
    displayName: "Golden Popcorn",
    details: "Gold will sometimes duplicate itself",
    rarity: rarity.common,
    type: type.relic,
    cost: 550,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "81b81569168949aeaea9412aea00601d": {
    name: "FoodPopcorn",
    displayName: "Seasoned Popcorn",
    details: "Food will sometimes duplicate itself",
    rarity: rarity.common,
    type: type.relic,
    cost: 550,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "586b91a55c884c48832f9503dd8947c2": {
    name: "CaramelPopcorn",
    displayName: "Caramel Popcorn",
    details: "Duplicated food packs a surprise",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 1100,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "ebb2f31ddd77460196d44fabcd18f57a": {
    name: "PocketGrill",
    displayName: "Pocket Grill",
    details: "Cooks all your food",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "6851f6a8812f4bcbabaa9a2414ec70d5": {
    name: "Leftovers",
    displayName: "Leftovers",
    details: "Find old, gross food in chests",
    rarity: rarity.common,
    type: type.relic,
    cost: 475,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "ed388fc9c09943bc987cf1c3388e8755": {
    name: "SpareOrdnance",
    displayName: "Spare Ordnance",
    details: "Discover a bomb in every chest",
    rarity: rarity.common,
    type: type.relic,
    cost: 450,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "f7eca5455bdf49fe9d2dafd4ec32d1e7": {
    name: "Miniaturizer",
    displayName: "Miniaturizer",
    details: "Find small boxes in big boxes",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 850,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "5abbafb002b04ee495f179afdb550ffa": {
    name: "KeyDoubler",
    displayName: "Key Doubler",
    details: "Sometimes drop a new key when using an old key",
    rarity: rarity.common,
    type: type.relic,
    cost: 480,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "e56c7298c19e47d990140eceb14b95cc": {
    name: "BombDoubler",
    displayName: "Bomb Doubler",
    details: "Sometimes drop a new bomb when using an old bomb",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 16,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "fb374cc41c744cdbbbe227889cf001c4": {
    name: "DoubleDoubler",
    displayName: "Double Doubler",
    details: "Chance to drop a key and bomb when using either",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 980,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "ec20d69533674c59a1af67db438bf172": {
    name: "PilfersGift",
    displayName: "Pilfer's Gift",
    details: "Be blessed with two gifts from the pilfers",
    rarity: rarity.rare,
    type: type.relic,
    cost: 900,
    craftingCost: 99,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "cad1d7d1cd454671ac62d6496c5aa49e": {
    name: "GoldenBombs",
    displayName: "Golden Powder",
    details: "Turns rock into gold",
    rarity: rarity.common,
    type: type.relic,
    cost: 750,
    craftingCost: 16,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "82d1d9ec3cb74d019e07ac5750e5433d": {
    name: "ClusterBombs",
    displayName: "Bombushka",
    details: "Bombs, in bombs, in bombs",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "04579544c0354d24a712f465b0a4a504": {
    name: "IncinediaryBombs",
    displayName: "Seer's Blood",
    details: "Bombs explode in a shower of fire",
    rarity: rarity.common,
    type: type.relic,
    cost: 350,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "96b62be9e4f04a329eed69ab143957aa": {
    name: "RookBombs",
    displayName: "Rook's Bomb",
    details: "Death at ninety degrees",
    rarity: rarity.common,
    type: type.relic,
    cost: 480,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "80c079e5b87345b28557d545c6f0131e": {
    name: "BishopBombs",
    displayName: "Bishop's Bomb",
    details: "Death at forty five degrees",
    rarity: rarity.common,
    type: type.relic,
    cost: 470,
    craftingCost: 8,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "78622bf8ccfb4b6b8f4ad11165615e88": {
    name: "QueensBombs",
    displayName: "Queen's Bomb",
    details: "Death in all directions",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 950,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "079a976e3dd24ea8819941b9f81259c2": {
    name: "TransmutagenBombs",
    displayName: "Transmutagen Blast",
    details: "Transforms items",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 1111,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "01dd414291604477aa1405b5683a29a3": {
    name: "BrandingBombs",
    displayName: "Branding Bomb",
    details: "Bombs brand enemies for sacrifice, +10 bombs",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 666,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "0948c27e6bf3483292c1e2e065499018": {
    name: "LightningBombs",
    displayName: "Lightning Bomb",
    details: "Bomb explosions chain lightning",
    rarity: rarity.common,
    type: type.relic,
    cost: 350,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "f3fc59fe276e4b5eb28425f43940c0f8": {
    name: "MidasBombs",
    displayName: "M.E.G.A. Bomb",
    details: "A mess of electrified gold",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 1100,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "5e270234064d40d08b17881eee751dfd": {
    name: "BloodBomb",
    displayName: "Blood Bomb",
    details: "Leeches life from enemies slain by bombs",
    rarity: rarity.common,
    type: type.relic,
    cost: 430,
    craftingCost: 10,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "7a06da12309d4136917c71be7772e055": {
    name: "TsarBomba",
    displayName: "Tsar Bomba",
    details: "Killing enemies with a bomb spawns two new bombs. Carried bombs decrease swing and throw damage.",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 875,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "c3cf34b72ca743f7986c53215ec3a358": {
    name: "U235",
    displayName: "U-235",
    details: "Bomb damage is proportional to the number of carried bombs, +5 bombs",
    rarity: rarity.rare,
    type: type.relic,
    cost: 560,
    craftingCost: 60,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "8c781614f3e545cd9dc53a1862f87dc7": {
    name: "Shrapnel",
    displayName: "Shrapnel",
    details: "Friendly bomb blasts fire projectiles",
    rarity: rarity.common,
    type: type.relic,
    cost: 310,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "3640d085d4624902a191cefbacabd840": {
    name: "GeckoBlast",
    displayName: "Gecko Blast",
    details: "Bomb blasts attract items",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "fd98fd90983c49f49e88267708a16807": {
    name: "CaptureSphere",
    displayName: "Capture Sphere",
    details: "Bomb kills permanently increase bomb damage",
    rarity: rarity.common,
    type: type.relic,
    cost: 285,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "a1231c3c35814d68aaae8d98cc882fd9": {
    name: "RemoteDetonator",
    displayName: "Remote Detonator",
    details: "Detonate bombs when you feel like it",
    rarity: rarity.rare,
    type: type.relic,
    cost: 375,
    craftingCost: 30,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "403c20cf86844b8ba5a495752f890817": {
    name: "ShortWicks",
    displayName: "Short Wicks",
    details: "Reduces the bomb cooldown",
    rarity: rarity.common,
    type: type.relic,
    cost: 225,
    craftingCost: 20,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "62b6f012430249ce8befe02ab52482db": {
    name: "MagnetizedOre",
    displayName: "Magnetized Ore",
    details: "Teleport enemies next to bombs",
    rarity: rarity.common,
    type: type.relic,
    cost: 350,
    craftingCost: 25,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "724a50c9ac524f9fb3f527a5052e02a6": {
    name: "Guantes",
    displayName: "Guantes",
    details: "Throw that pickaxe a bit harder",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 10,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "1808d1da72b540c1a611a560f5f89fb3": {
    name: "SequenceBreaker",
    displayName: "Sequence Breaker",
    details: "Teleport to your pickaxe",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 26,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "67aea971b4214697bb0cf4bdc4e904aa": {
    name: "ThrowingStar",
    displayName: "Throwing Star",
    details: "Thrown pickaxe penetrates enemies and objects",
    rarity: rarity.common,
    type: type.relic,
    cost: 350,
    craftingCost: 16,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "b4e5f598694c439d8260e8539e0320b2": {
    name: "Guidance",
    displayName: "Guidance",
    details: "Ricochet the thrown pickaxe",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "01e0ef72372d4531a4a1cdb3cc265f97": {
    name: "PhantasmalAxe",
    displayName: "Phantasmal Axe",
    details: "Thrown pickaxes duplicate themselves",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "830216e9492c484489ef90c303f07b68": {
    name: "Chakram",
    displayName: "Chakram",
    details: "Throw a whirling blade of death",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 800,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "48f2bb8ba1f742ca830edfaa91772625": {
    name: "Fork",
    displayName: "Fork",
    details: "Splits your ranged attacks",
    rarity: rarity.rare,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "b6f58486915b43b8bcd0004d74f9182b": {
    name: "BottledLightning",
    displayName: "Bottled Lightning",
    details: "Chance on hit to chain lightning",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "efa267f58ead4081a7c8d7769a5e6bf8": {
    name: "SalamanderTail",
    displayName: "Salamander Tail",
    details: "Chance on hit to ignite your enemies",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "aede3a51037549b9b0eeeec881d5168e": {
    name: "Crippling Poison",
    displayName: "Crippling Poison",
    details: "Chance on hit to poison your enemies",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 14,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "e25c4adfa3e04022ae18673db8f83276": {
    name: "CausticVial",
    displayName: "Caustic Vial",
    details: "Enemies hit with the thrown pickaxe explode on death",
    rarity: rarity.common,
    type: type.relic,
    cost: 375,
    craftingCost: 24,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "0c33fc50f8d94d518803789c0b7f2185": {
    name: "Cracked Orb",
    displayName: "Cracked Orb",
    details: "Curse enemies with increased damage",
    rarity: rarity.rare,
    type: type.relic,
    cost: 460,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "9fcfbe4652be48ec82ea6a8431a18d37": {
    name: "UrsineRing",
    displayName: "Ursine Ring",
    details: "Increase health",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "29799d6270d24f018cef3d360eebc5e7": {
    name: "DemonRing",
    displayName: "Demon Ring",
    details: "Increase swing damage",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "651c313904884b19afcd5a1da136c01c": {
    name: "MediocreRing",
    displayName: "Mediocre Ring",
    details: "Increases health and damage",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 8,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "3693999de5e94fcd81b5fcd53c13e8b4": {
    name: "BerserkerPendant",
    displayName: "Berserker's Pendant",
    details: "Deal more swing damage at low health",
    rarity: rarity.common,
    type: type.relic,
    cost: 420,
    craftingCost: 20,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2fe62c4bfc084a7a8516c18f23575fb3": {
    name: "AxeThrowersPendant",
    displayName: "Axe Thrower's Pendant",
    details: "Deal more throw damage at low health",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "10444b01cc944bdc92bbc183ecfd4dfe": {
    name: "KnightPendant",
    displayName: "Knight's Pendant",
    details: "Deal more swing damage at high health",
    rarity: rarity.common,
    type: type.relic,
    cost: 420,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "77af6531c8294f249cf55fd69c74bd8a": {
    name: "ArchersPendant",
    displayName: "Archer's Pendant",
    details: "Deal more throw damage at high health",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 20,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "e790a903a95240ffa6ff75f0c17475cd": {
    name: "Iron Branch",
    displayName: "Iron Branch",
    details: "Increase health, swing damage, and attack speed",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "e21cf8a29a6b4277b40ba59cb04c299b": {
    name: "CrownQueens",
    displayName: "Queen's Crown",
    details: "Increase throw damage, swing size, and swing speed",
    rarity: rarity.rare,
    type: type.relic,
    cost: 550,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "0248a19ceeb042c096a827dbcb5b10de": {
    name: "CrownKings",
    displayName: "King's Crown",
    details: "Increase swing damage, throw size, and throw speed",
    rarity: rarity.rare,
    type: type.relic,
    cost: 550,
    craftingCost: 26,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "5efb8642758041cfb29b8555ce405f41": {
    name: "CrownEmperors",
    displayName: "Emperor's Crown",
    details: "Increases stats and receive a blessing",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 1100,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "6e31da144f9b4820a3442e42883a52e5": {
    name: "PilferRing",
    displayName: "Pilfer Ring",
    details: "Soak up gold and get a discount at the shop",
    rarity: rarity.common,
    type: type.relic,
    cost: 800,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "7c1a74b4bc5e4398b2a10459f9b50b21": {
    name: "UnstableConcoction",
    displayName: "Unstable Concoction",
    details: "Gold hits the floor with explosive force",
    rarity: rarity.common,
    type: type.relic,
    cost: 420,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "9c707dd6871a44b7b7326ad378f41a38": {
    name: "GoldTooth",
    displayName: "Gold Tooth",
    details: "Sustain yourself on gold",
    rarity: rarity.common,
    type: type.relic,
    cost: 600,
    craftingCost: 15,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "ebe6a743ac76455ea4771e300ebc0b7b": {
    name: "Golden Delicious",
    displayName: "Golden Delicious",
    details: "All food is golden and extra delicious",
    rarity: rarity.common,
    type: type.relic,
    cost: 150,
    craftingCost: 8,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "277d2316237d49109d6d1439f7df6e14": {
    name: "Conductor",
    displayName: "Conductor",
    details: "Electrify your enemies when picking up gold",
    rarity: rarity.common,
    type: type.relic,
    cost: 550,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "0533edf2633049baa08a73d7ba5ef518": {
    name: "Gold Frenzy",
    displayName: "Gold Frenzy",
    details: "Gain temporary damage when picking up gold",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "872540dbf7be4f2c9ce3a79f346c41a7": {
    name: "LuckyNugget",
    displayName: "Lucky Nugget",
    details: "Enemies drop gold when critically hit",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 45,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "7c3dcc99d36d4f6f8bcc2524ecdb93e8": {
    name: "Intensifier",
    displayName: "Intensifier",
    details: "Increases damage when killing enemies",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "a596ffca42664024be1aeba28ad46f24": {
    name: "SkullShield",
    displayName: "Floating Skull",
    details: "A shield that blocks projectiles, most of the time",
    rarity: rarity.rare,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "23ed5e24dd3c420eacbf5c006e61be87": {
    name: "ReflectProjectiles",
    displayName: "Grimhilde's Mirror",
    details: "Return projectiles with an attack",
    rarity: rarity.common,
    type: type.relic,
    cost: 350,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "db4baf760be740b99ff679a838ee3ee4": {
    name: "MirrorShield",
    displayName: "Mirror Shield",
    details: "Automatically reflect projectiles",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 750,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "91f466ecbb87497b943eabd77f6e4681": {
    name: "HungrySpirit",
    displayName: "Hungry Ghost",
    details: "Leach the life of your enemies",
    rarity: rarity.rare,
    type: type.relic,
    cost: 480,
    craftingCost: 25,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "dd44a1f545ad48cda6d653cb6b5eaafb": {
    name: "Nullstone",
    displayName: "Nullstone",
    details: "Block a hit once in a while",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 650,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "35ccd3bee9604d10988601bfecb53a3a": {
    name: "Mushroom",
    displayName: "Mushroom",
    details: "Gain maximum health when killing enemies",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 540,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "eaf60a76dda742928cdd8f75d3e22eca": {
    name: "Clover",
    displayName: "Four Leaf Clover",
    details: "Hit the gold right out of your enemies' pockets",
    rarity: rarity.rare,
    type: type.relic,
    cost: 525,
    craftingCost: 22,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "69994ce940d94e439ab01d04a9c176e7": {
    name: "Tent",
    displayName: "Tent",
    details: "Adds a tent to the starting room of a floor, one use only",
    rarity: rarity.common,
    type: type.relic,
    cost: 300,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "56fb37c63e434aa08fa3c868c3c4d9c3": {
    name: "Aegis",
    displayName: "Aegis",
    details: "Increase defense at critical health",
    rarity: rarity.common,
    type: type.relic,
    cost: 350,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "fdf3edb47a594d0f870acabb1d82d433": {
    name: "Map",
    displayName: "Map",
    details: "Get a peep at your surroundings",
    rarity: rarity.rare,
    type: type.relic,
    cost: 250,
    craftingCost: 20,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "43637fecaef7443482c195c01ede0a32": {
    name: "Bounty Contract",
    displayName: "Bounty Contract",
    details: "Adds a bounty to a random enemy",
    rarity: rarity.common,
    type: type.relic,
    cost: 425,
    craftingCost: 30,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "d537cbb8584b4a3fbe45f0ceef4f2ef1": {
    name: "Petrified Rock",
    displayName: "Petrified Rock",
    details: "Increase drop rate of items from rocks",
    rarity: rarity.rare,
    type: type.relic,
    cost: 999,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "3776afb876a74e50911b6d3080f0388d": {
    name: "Rat Bond",
    displayName: "Rat Bond",
    details: "Become charming to rats",
    rarity: rarity.rare,
    type: type.relic,
    cost: 250,
    craftingCost: 15,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "97fbd863c09b44fa9605e675e7275f85": {
    name: "Cosmic Egg",
    displayName: "Cosmic Egg",
    details: "Increases experience gain for a familiar",
    rarity: rarity.rare,
    type: type.relic,
    cost: 750,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "3d321813e7904a1486d6243defa59cc3": {
    name: "Birthing Pod",
    displayName: "Birthing Pod",
    details: "Consumes all healing until birth",
    rarity: rarity.common,
    type: type.relic,
    cost: 0,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "898d87f98b184697ac89672f9bf955e4": {
    name: "CreditCardSilver",
    displayName: "Pilfer Credit Card Silver",
    details: "A 2,500 limit at 0% interest!",
    rarity: rarity.common,
    type: type.relic,
    cost: 1,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "f83c843bf28e48afbb6f3aec7d5d0eed": {
    name: "CreditCardGold",
    displayName: "Pilfer Credit Card Gold",
    details: "A 5,000 limit at 0% interest!",
    rarity: rarity.rare,
    type: type.relic,
    cost: 1,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "87dd4661d57b48c3812b4c962c00cc2e": {
    name: "CreditCardBlack",
    displayName: "Pilfer Credit Card Black Edition",
    details: "7,500 limit and 5% cash back!",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 2,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "189b6fc98b1849ea848523610481af7d": {
    name: "ButchersClover",
    displayName: "Four Leaf Cleaver",
    details: "Sometimes drop golden meat from your enemies",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 1050,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "f3973f00fda94bfbb4eed373ed28b775": {
    name: "RabbitGloves",
    displayName: "Rabbit Gloves",
    details: "Get a free item in every shop",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 1200,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "4202645d8fa34a97a70ded11ee0f8f31": {
    name: "KarmicScale",
    displayName: "Karmic Scale",
    details: "Health, damage, and healing become small and even",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 1100,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "bab552535a104b059e636abfd7d05685": {
    name: "PocketOfHolding",
    displayName: "Pocket of Holding",
    details: "Get some temporary bombs each room",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 550,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "4cf72d4585f64a95b4d614bd559e4d58": {
    name: "Lockpick",
    displayName: "Lockpick",
    details: "Open locks for free, but for how long?",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 900,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "5a5b61097a034cfeb6858d2d6c809af0": {
    name: "LuckyCharm",
    displayName: "Lucky Charm",
    details: "A chance at avoiding death",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 38,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "52d4e1bd77c84ec790991cf8e87d2ebc": {
    name: "LuckyLockpick",
    displayName: "Lucky Lockpick",
    details: "A chance to not die, and no chance to break",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 1300,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "7b5f646318f3454dacb28fc75eb8c0f2": {
    name: "Inverter",
    displayName: "Inverter",
    details: "Lost curses become blessings",
    rarity: rarity.rare,
    type: type.relic,
    cost: 475,
    craftingCost: 25,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "82b826e6d3044504bfa46c4caa6f1b0b": {
    name: "Recycler",
    displayName: "Recycler",
    details: "Destroy empty chests for items",
    rarity: rarity.common,
    type: type.relic,
    cost: 375,
    craftingCost: 20,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "0682d92aff14474d895c2e91f8826f25": {
    name: "FanOfKnives",
    displayName: "Fan of Knives",
    details: "Release a spray of daggers when you throw",
    rarity: rarity.common,
    type: type.relic,
    cost: 500,
    craftingCost: 16,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "f5e0082e84c74286829fa52bf633cbeb": {
    name: "KurtzStache",
    displayName: "Kurtz' Stache",
    details: "A mysterious box that invites calamity",
    rarity: rarity.common,
    type: type.relic,
    cost: 200,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "b7a8798a25ca4137a95538358085f2f4": {
    name: "GlassCannon",
    displayName: "Glass Cannon",
    details: "Increases damage, but decreases maximum health",
    rarity: rarity.legendary,
    type: type.relic,
    cost: 775,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "2e8dd836a09f4e47b57e23b4d00f16ec": {
    name: "SoulCannon",
    displayName: "Soul Cannon",
    details: "Fire a projectile while swinging",
    rarity: rarity.rare,
    type: type.relic,
    cost: 550,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "ecc0480e43924477ad68b3e9beb631b3": {
    name: "Ara",
    displayName: "Ara",
    details: "Temporarily consumes a future curse after praying",
    rarity: rarity.common,
    type: type.relic,
    cost: 425,
    craftingCost: 26,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "6ca902940c004d7c957fe367f77e7337": {
    name: "UrsaMajor",
    displayName: "Ursa Major",
    details: "Temporarily increases max health after eating food",
    rarity: rarity.common,
    type: type.relic,
    cost: 400,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "4ca66dcd2df34cbcbef82e2c5cafd5fc": {
    name: "CanisMajor",
    displayName: "Canis Major",
    details: "Crits temporarily increase crit chance",
    rarity: rarity.common,
    type: type.relic,
    cost: 300,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "993daf5814304f9da36d0080fe4b9cbc": {
    name: "Sagitta",
    displayName: "Sagitta",
    details: "Enemies temporarily explode in arrows after a critical strike",
    rarity: rarity.common,
    type: type.relic,
    cost: 325,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "7aedab48d5ca4e5b8d9f33a292ef38ef": {
    name: "Circinus",
    displayName: "Circinus",
    details: "Temporarily reveals secret rooms, secret rooms can have secret rooms",
    rarity: rarity.common,
    type: type.relic,
    cost: 380,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "e7cb0d0449d640baa7d05b92994d34ce": {
    name: "OrionsSword",
    displayName: "Orion's Sword",
    details: "Temporarily increase damage when attacked",
    rarity: rarity.common,
    type: type.relic,
    cost: 375,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "24e76c8b632c48f78b0a3060d4d1f786": {
    name: "CursedAegis",
    displayName: "Siegfried's Aegis",
    details: "Inflicts pain on the bearer",
    rarity: rarity.common,
    type: type.relic,
    cost: 1,
    craftingCost: 1,
    active: false,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "a6587dfd53e54a20ab1a167bc2b40e4a": {
    name: "PaladinShield",
    displayName: "Paladin Shield",
    details: "",
    rarity: rarity.rare,
    type: type.relic,
    cost: 0,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
  "5445617cf5a24b678e1680f88ba4f134": {
    name: "Hot Cross Bun",
    displayName: "Hot Cross Bun",
    details: "Increases maximum health, very slightly",
    rarity: rarity.common,
    type: type.relic,
    cost: 5,
    craftingCost: 0,
    active: true,
    found: 0,
    maxFound: 1,
    extra: () => {return},
  },
}