const maps = {

  mineTutorial: {
    default:{zone:"mine"},
    levels: [
      rooms("tuBegin", "tuJump", "tuAttack", "tuBomb", "tuThrow", "tuPilfer", "tuRelic", "tuEnd"),
    ]
  },

	mineEarly: {
		default:{zone:"mine"},
		levels: [
      [
			  rooms("begin", "easy", "easy", "easy", "end"),
        ...rooms.multi(
          "relicUnlocked",
          "treasureBasic",
          "treasureBasicChance",
          "secret",
          "secret",
          "secretChance",
          "hoody",
          "hidden",
          "relicAltar",
        ),
      ],
      [
        rooms("begin", "normal", "normal", "normal", "end"),
        rooms("waylandHallway", "waylandShop"),
        ...rooms.multi(
          "relic",
          "altar",
          "treasureBasic",
          "treasureBasicChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltar",
        ),
      ],
      [
        rooms("begin", "normal", "normal"),
        rooms("dodsonCage", "mimicFight", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltar",
        ),
      ],
      [
        rooms("begin"),
        rooms("normal", "normal", "normal", "normal", "endBossSmall"),
        rooms("prechamber", "nextDown"),
        ...rooms.multi(
          "relic",
          "altar",
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "bossRoom",
          "hidden",
          "relicAltar",
        ),
      ],
    ],
  },

  mine: {
    default: {zone:"mine"},
    levels: [
      [
        rooms("begin", "normal", "normalLarge", "normal", "normalLarge", "end"),
        ...rooms.multi(
          "relicUnlocked",
          "blackRabbitFirst",          
          "treasure",
          "treasureChance",
          "altar",
          "secret",
          "secret",
          "secretChance",
          "hoody",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normal", "normalLarge", "normal", "normalLarge", "end"),
        rooms("waylandHallway", "waylandShop"),
        ...rooms.multi(
          "relic",
          "apprentice",     
          "mushroom",     
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normal", "normalLarge"),
        rooms("dodsonCage", "mimicFight", "end"),
        ...rooms.multi(
          "relic",
          "apprentice",
          "mushroom",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "blackRabbit",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin"),
        rooms("normal", "normalLarge", "normal", "normalLarge", "endBossSmall"),
        rooms("prechamber", "nextDown"),
        ...rooms.multi(
          "relic",
          "apprentice",     
          "mushroom",     
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "bossRoom",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
    ],
  },

  dungeon: {
    default: {zone:"dungeon"},
    levels: [
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "dibble",
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "mastersKey",
          "secret",
          "secret",
          "secretChance",
          "priestess",
          "hoody",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "mastersKey",
          "secret",
          "secret",
          "secretChance",
          "priestess",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "blackRabbit",
          "mastersKey",
          "secret",
          "secret",
          "secretChance",
          "priestess",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "endBoss"),
        rooms("prechamber", "nextDown"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "mastersKey",
          "secret",
          "secret",
          "secretChance",
          "bossRoom",
          "priestess",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
    ]
  },

  dungeonBug: {
    default: {zone:"dungeon"},
    levels: [
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "dibble",
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "mastersKey",
          "secret",
          "secret",
          "secretChance",
          "hoody",
          "priestess",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
    ],
  },

  hall: {
    default: {zone:"hall"},
    levels: [
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "libraryCombat",
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "secret",
          "secret",
          "secretChance",
          "hoody",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "blackRabbit",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "endBoss"),
        rooms("prechamber", "nextDown"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "bossRoom",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
    ],
  },

  cavern: {
    default: {zone:"cavern"},
    levels: [
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "secret",
          "secret",
          "secretChance",
          "hoody",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "blackReddit",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "endBoss"),
        rooms("prechamber", "nextDown"),
        rooms("bogPrechamber", "bogDown"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "bossRoom",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ],
    ]
  },

  cavernBug: {
    default: {zone:"cavern"},
    levels: [
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "endBoss"),
        rooms("prechamber", "nextDown"),
        rooms("bogPrechamberBug", "bogDownBug"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "bossRoom",
          "hidden",
          "relicAltar",
          "fountain",
        ),
      ]
    ]
  },

  core: {
    default: {zone:"core"},
    levels: [
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltarLastFloors",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltarLastFloors",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "altar",
          "blackRabbit",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltarLastFloors",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "endBoss"),
        ...rooms.multi(
          "relic",
          "treasure",
          "treasureChance",
          "shop",
          "secret",
          "secret",
          "secretChance",
          "bossRoom",
          "hidden",
          "relicAltarLastFloors",
        ),
      ],
    ],
  },

  bog: {
    default: {zone:"bog"},
    levels: [
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relicExtraCost",
          "treasure",
          "treasureChance",
          "shopExtraCost",
          "altar",
          "royalRoad0",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltarLastFloors",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relicExtraCost",
          "treasure",
          "treasureChance",
          "shopExtraCost",
          "royalRoad0",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltarLastFloors",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "end"),
        ...rooms.multi(
          "relicExtraCost",
          "treasure",
          "treasureChance",
          "shopExtraCost",
          "altar",
          "blackRabbit",
          "royalRoad0",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "relicAltarLastFloors",
        ),
      ],
      [
        rooms("begin", "normalLarge", "normal", "normalLarge", "normalLarge", "endBoss"),
        ...rooms.multi(
          "relicExtraCost",
          "treasure",
          "treasureChance",
          "shopExtraCost",
          "royalRoad0",
          "secret",
          "secret",
          "secretChance",
          "hidden",
          "bossRoom",
          "relicAltarLastFloors",
        ),
      ],
    ]
  }
}