const maps = {

  mineTutorial: {
    default:{zone:"mine"},
    levels: [
        [
          {stage:["small"], tags:"begin_tutorial", branchWeight: 1},
          {stage:["small"], tags:"tutorial_jump", direction: 2, branchWeight: 1},
          {stage:["small"], tags:"tutorial_attack", direction: 2, branchWeight: 1},
          {stage:["small"], tags:"tutorial_bomb", direction: 4, branchWeight: 1},
          {stage:["large"], tags:"tutorial_throw", direction: 1, branchWeight: 1},
          {stage:["large"], tags:"tutorial_pilfer", direction: 4, branchWeight: 1},
          {stage:["small"], tags:"tutorial_relic", direction: 1, branchWeight: 1},
          {stage:["small"], tags:"end_tutorial", direction: 1, branchWeight: 1},
        ],
    ]
  },

	mineEarly: {
		default:{zone:"mine"},
		levels: [
      [
			  [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["small"], tags:"easy", branchWeight: 4},
          {stage:["small"], tags:"easy", branchWeight: 4},
          {stage:["small"], tags:"easy", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
			  ],
			  [ {stage:["small"], tags:"relic_unlocked", branchWeight: 1} ],
			  [ {stage:["small"], tags:"treasure_basic_encounters", branchWeight: 1} ],
			  [ {stage:["small","large"], tags:"treasure_basic_encounters", chance: 0.5, requirements:requirements.hasWhip} ],
			  [ {stage:["small","large"], tags:"secret"} ],
			  [ {stage:["small","large"], tags:"secret"} ],
			  [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
			  [ {stage:["extra"], tags:"hoody"} ],
			  [ {stage:["small","large"], tags:"hidden"} ],
			  [	{stage:["large"], tags:"relic_altar", chance: 0.0625} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [
          {stage:["small"], tags:"waylandshophallway"},
          {stage:["small"], tags:"waylandshop", direction: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small"], tags:"altar"} ],
        [ {stage:["small"], tags:"treasure_basic_encounters", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure_basic_encounters", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"}, ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.125} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
        ],
        [
          {stage:["small"], tags:"DodsonCageEncounter,normal", branchWeight: 4},
          {stage:["large"], tags:"RockMimicEncounter,normal"},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.1875} ],
      ],
      [
        [ {stage:["small"], tags:"begin", branchWeight: 4} ],
        [
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end_worm"},
        ],
        [
          {stage:["large"], tags:"", branchWeight: 1},
          {zone:"dungeon", stage:["small"], tags:"dungeon_entrance", direction: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small"], tags:"altar"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"sandRoom"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.25} ],
      ],
    ],
  },

  mine: {
    default: {zone:"mine"},
    levels: [
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic_unlocked", branchWeight: 1} ],
        [ {stage:["small"], tags:"black_rabbit_first", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"hoody"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.0625} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.0625} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [
          {stage:["small"], tags:"waylandshophallway"},
          {stage:["small"], tags:"waylandshop", direction: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["large"], tags:"mushroom_apprentice", branchWeight: 1, chance: 0.5} ],
        [ {stage:["small","large"], tags:"mushroom", chance: 0.6} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.125} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.125} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
        ],
        [
          {stage:["small"], tags:"DodsonCageEncounter,normal", branchWeight: 4},
          {stage:["large"], tags:"RockMimicEncounter,normal"},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["large"], tags:"mushroom_apprentice", branchWeight: 1, chance: 0.7} ],
        [ {stage:["small","large"], tags:"mushroom", chance: 0.7} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["extra"], tags:"black_rabbit", chance: 0.5} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.1875} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.1875} ],
      ],
      [
        [ {stage:["small"], tags:"begin", branchWeight: 4} ],
        [
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end_worm"},
        ],
        [
          {stage:["large"], tags:"", branchWeight: 1},
          {zone:"dungeon", stage:["small"], tags:"dungeon_entrance", direction: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["large"], tags:"mushroom_apprentice", branchWeight: 1, chance: 0.9} ],
        [ {stage:["small","large"], tags:"mushroom", chance: 0.8} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"sandRoom"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.25} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.25} ],
      ],
    ],
  },

  dungeon: {
    default: {zone:"dungeon"},
    levels: [
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["large"], tags:"dibble", direction: 1} ],
        [ {stage:["small","large"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["large"], tags:"masters_key"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small"], tags:"priestess"} ],
        [ {stage:["extra"], tags:"hoody"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.3125} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.3125} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small","large"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar"} ],
        [ {stage:["large"], tags:"masters_key"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small"], tags:"priestess"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.375} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.375} ]
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small","large"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["extra"], tags:"black_rabbit", chance: 0.5} ],
        [ {stage:["large"], tags:"masters_key"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [  {stage:["small"], tags:"priestess"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.4375} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.4375} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"end_stone", branchWeight: 1},
        ],
        [
          {stage:["large"], tags:"", direction: 1},
          {stage:["small"], tags:"hall_entrance", direction: 1},
        ],
        [ {stage:["small","large"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar"} ],
        [ {stage:["large"], tags:"masters_key"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"boss"} ],
        [ {stage:["small"], tags:"priestess"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.5} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.5} ],
      ],
    ]
  },

  dungeonBug: {
    default: {zone:"dungeon"},
    levels: [
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["large"], tags:"dibble", direction: 1} ],
        [ {stage:["small","large"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["large"], tags:"masters_key"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"hoody"} ],
        [ {stage:["small"], tags:"priestess"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.3125} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.3125} ],
      ],
    ],
  },

  hall: {
    default: {zone:"hall"},
    levels: [
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["large"], tags:"hall_library_combat_arena", branchWeight: 1} ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"hoody"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.5625} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.5625} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.625}, ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.625} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["extra"], tags:"black_rabbit", chance: 0.5} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.6875} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.6875} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"end_shadow", branchWeight: 1},
        ],
        [
          {stage:["large"], tags:"", direction: 1},
          {zone:"cavern", stage:["small"], tags:"cavern_entrance", direction: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"boss"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.75} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.75} ],
      ],
    ],
  },

  cavern: {
    default: {zone:"cavern"},
    levels: [
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"hoody"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.8125} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.8125} ]
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.875} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.875} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["extra"], tags:"black_rabbit", chance: 0.5} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.9375} ],
        [ {stage:["small"], tags:"tribute_fountain", chance: 0.9375} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"down_crystallord", branchWeight: 1},
        ],
        [
          {stage:["large"], tags:"", direction: 1},
          {zone:"core", stage:["small"], tags:"core_entrance", direction: 1},
        ],
        [
          {stage:["large"], tags:"", direction: 1},
          {zone:"bog", stage:["small"], tags:"bog_entrance", direction: 1},
        ],
 
        [ {stage:["extra"], tags:"boss"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar"} ],
        [ {stage:["small"], tags:"tribute_fountain"} ]
      ],
    ]
  },

  cavernBug: {
    default: {zone:"cavern"},
    levels: [
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"down_crystallord", branchWeight: 1},
        ],
        [
          {stage:["large"], tags:"", direction: 1},
          {zone:"core", stage:["small"], tags:"core_entrance", direction: 1},
        ],
        [
          {stage:["large"], tags:""},
          {zone:"bog", stage:["small"], tags:"bog_entrance"},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"boss"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar"} ],
        [ {stage:["small"], tags:"tribute_fountain"} ],
      ]
    ]
  },

  core: {
    default: {zone:"core"},
    levels: [
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.8125}, ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.875} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["extra"], tags:"black_rabbit", chance: 0.5} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.9375} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"down_firelord", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["extra"], tags:"boss"} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar"} ],
      ],
    ],
  },

  bog: {
    default: {zone:"bog"},
    levels: [
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic", doorCost: "2 keys"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1, doorCost: "2 keys"} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["large"], tags:"royal_road_0", chance: 0.25} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.8125} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic", doorCost:"2 keys"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1, doorCost: "2 keys"} ],
        [ {stage:["large"], tags:"royal_road_0", chance: 0.5} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.875} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small"], tags:"end", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic", doorCost:"2 keys"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1, doorCost:"2 keys"} ],
        [ {stage:["small"], tags:"altar", branchWeight: 1} ],
        [ {stage:["extra"], tags:"black_rabbit", chance: 0.5} ],
        [ {stage:["large"], tags:"royal_road_0", chance: 0.75} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["large"], tags:"relic_altar", chance: 0.9375} ],
      ],
      [
        [
          {stage:["small"], tags:"begin", branchWeight: 1},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["small","large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"normal", branchWeight: 4},
          {stage:["large"], tags:"down_pk", branchWeight: 1},
        ],
        [ {stage:["small"], tags:"relic", doorCost:"2keys"} ],
        [ {stage:["small","large"], tags:"treasure", branchWeight: 1} ],
        [ {stage:["small","large"], tags:"treasure", chance: 0.5, requirements:requirements.hasWhip} ],
        [ {stage:["extra"], tags:"shop", branchWeight: 1, doorCost:"2keys"} ],
        [ {stage:["large"], tags:"royal_road_0"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret"} ],
        [ {stage:["small","large"], tags:"secret", chance: 0.5, requirements:requirements.hasHat} ],
        [ {stage:["small","large"], tags:"hidden"} ],
        [ {stage:["extra"], tags:"boss"} ],
        [ {stage:["large"], tags:"relic_altar"} ]
      ],
    ]
  }
}