interface Zone {
  name:string;
  map:string;
  zoneNumber:number;
  startFloor:number;
  baseDifficulty:number;
  difficultyStep:number;
  enemyTypeWeight:number[];
  requirements:Function;
  floors:any[];
}

const zoneData:Zone[][] = [
  [ //mine
    {
      name:"mineTutorial",
      map:"mineEarly",
      zoneNumber: 1,
      startFloor: 1,
      baseDifficulty: 2,
      difficultyStep: 3,
      enemyTypeWeight:[0,1,2],
      requirements: conditions.tutorialIncomplete,
      floors: [
        {
          override: {
            map:"mineTutorial",
          },
          enemies: [],
        },
        {
          enemies: [
            enemies.ratBasic,
            enemies.jumperWater,
            enemies.flyRanged,
          ],
        },
        {
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperWater,
            enemies.ratNest,
          ],
        },
        {
          override: {
            difficulty: 10,
            enemyTypeWeight:[0,1,2,1],
          },
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.jumperWater,
            enemies.jumperOli,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
          ],
        },
      ],
    },
    {
      name:"mine1",
      map:"mineEarly",
      zoneNumber: 1,
      startFloor: 1,
      baseDifficulty: 3,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2],
      requirements: conditions.tutorialComplete,
      floors: [
        {
          enemies: [
            enemies.ratBasic,
            enemies.jumperWater,
            enemies.flyRanged,
          ],
        },
        {
          enemies: [
            enemies.ratBasic,
            enemies.jumperWater,
            enemies.flyRanged,
          ],
        },
        {
          override: {
            difficulty: 8,
          },
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperWater,
            enemies.ratNest,
          ],
        },
        {
          override: {
            difficulty: 10,
            enemyTypeWeight:[0,1,2,1],
          },
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.jumperWater,
            enemies.jumperOli,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
          ],
        },
      ],
    },
    {
      name:"mine2",
      map:"mine",
      zoneNumber: 1,
      startFloor: 1,
      baseDifficulty: 5,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.mimicKilled,
      floors: [
        {
          override: {
            enemyTypeWeight:[0,1,2],
          },
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperWater,
            enemies.ratNest,
          ],
        },
        {
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.ratTough,
          ],
        },
        {
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
          ],
        },
        {
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
          ],
        },
      ],
    },
    {
      name:"mine3",
      map:"mine",
      zoneNumber: 1,
      startFloor: 1,
      baseDifficulty: 8,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.mineSandwormKilled,
      floors: [
        {
          override: {
            enemyTypeWeight:[0,1,2],
          },
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.ratTough,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bat,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
      ],
    },
    {
      name:"mine4",
      map:"mine",
      zoneNumber: 1,
      startFloor: 1,
      baseDifficulty: 12,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.mineStonelordKilled,
      floors: [
        {
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.ratTough,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.ogreBombardier,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bat,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
      ],
    },
    {
      name:"mine5",
      map:"mine",
      zoneNumber: 1,
      startFloor: 1,
      baseDifficulty: 16,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.mineShadowlordKilled,
      floors: [
        {
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.ratTough,
            enemies.bobo,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bat,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bat,
            enemies.shaman,
            enemies.bugLightning,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
      ],
    },
  ],
  [ //dungeon
    {
      name:"dungeon1",
      map:"dungeon",
      zoneNumber: 2,
      startFloor: 6,
      baseDifficulty: 12,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.allBossesAlive,
      floors: [
        {
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.ratTough,
            enemies.ratLarge,
            enemies.bat,
            enemies.spiderBasic,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.crossbowman,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          override: {
            enemyTypeWeight:[0,0,2,1],
          },
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          override: {
            enemyTypeWeight:[0,0,2,1],
          },
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
      ],
    },
    {
      name:"dungeon2",
      map:"dungeon",
      zoneNumber: 2,
      startFloor: 6,
      baseDifficulty: 16,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.sandwormKilled,
      floors: [
        {
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.crossbowman,
            enemies.bishFish,
            enemies.rookFish,
            enemies.goblinEngineer,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
            enemies.goblinEngineer,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
      ],
    },
    {
      name:"dungeon3",
      map:"dungeon",
      zoneNumber: 2,
      startFloor: 6,
      baseDifficulty: 20,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.stonelordKilled,
      floors: [
        {
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.crossbowman,
            enemies.goblinEngineer,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.crossbowman,
          ],
        },
      ],
    },
    {
      name:"dungeon4",
      map:"dungeon",
      zoneNumber: 2,
      startFloor: 6,
      baseDifficulty: 24,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.shadowlordKilled,
      floors: [
        {
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.crossbowman,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.skeletonEnemyNorm,
            enemies.gargoyle,
            enemies.gargoyleStatue,
            enemies.crossbowman,
          ],
        },
      ],
    },
    {
      name:"dungeon5",
      map:"dungeon",
      zoneNumber: 2,
      startFloor: 6,
      baseDifficulty: 28,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.crystallordKilled,
      floors: [
        {
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.crossbowman,
          ],
        },
        {
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.skeletonEnemyNorm,
            enemies.gargoyle,
            enemies.gargoyleStatue,
            enemies.crossbowman,
          ],
        },
      ],
    },
  ],
  [ //hall
    {
      name:"hall1",
      map:"hall",
      zoneNumber: 3,
      startFloor: 11,
      baseDifficulty: 20,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.stonelordNotKilled,
      floors: [
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.skeletonEnemyNorm,
            enemies.lurkerCrypt,
            enemies.jumperWaterLarge,
            enemies.spiderWolf,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.skeletonEnemyNorm,
            enemies.lurkerCrypt,
            enemies.throwbo,
            enemies.spiderWolf,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.throwbo,
            enemies.lurkerCrypt,
            enemies.spiderWolf,
            enemies.assassin,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyle,
            enemies.gargoyleStatue,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.throwbo,
            enemies.lurkerCrypt,
            enemies.spiderWolf,
            enemies.assassin,
            enemies.goblinTickerEngineer,
          ],
        },
      ],
    },
    {
      name:"hall2",
      map:"hall",
      zoneNumber: 3,
      startFloor: 11,
      baseDifficulty: 24,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.stonelordKilled,
      floors: [
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.skeletonEnemyNorm,
            enemies.lurkerCrypt,
            enemies.jumperWaterLarge,
            enemies.spiderWolf,
            enemies.throwbo,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.lurkerCrypt,
            enemies.throwbo,
            enemies.spiderWolf,
            enemies.assassin,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.throwbo,
            enemies.lurkerCrypt,
            enemies.spiderWolf,
            enemies.assassin,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyle,
            enemies.gargoyleStatue,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.throwbo,
            enemies.lurkerCrypt,
            enemies.spiderWolf,
            enemies.assassin,
            enemies.goblinTickerEngineer,
          ],
        },
      ],
    },
    {
      name:"hall3",
      map:"hall",
      zoneNumber: 3,
      startFloor: 11,
      baseDifficulty: 28,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.shadowlordKilled,
      floors: [
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.lurkerCrypt,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.spiderWolf,
            enemies.throwbo,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.lurkerCrypt,
            enemies.throwbo,
            enemies.spiderWolf,
            enemies.assassin,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.throwbo,
            enemies.lurkerCrypt,
            enemies.spiderWolf,
            enemies.assassin,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyle,
            enemies.gargoyleStatue,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.throwbo,
            enemies.lurkerCrypt,
            enemies.spiderWolf,
            enemies.assassin,
            enemies.goblinTickerEngineer,
          ],
        },
      ],
    },
    {
      name:"hall4",
      map:"hall",
      zoneNumber: 3,
      startFloor: 11,
      baseDifficulty: 28,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,2,1],
      requirements: conditions.crystallordKilled,
      floors: [
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.lurkerCrypt,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.spiderWolf,
            enemies.throwbo,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.lurkerCrypt,
            enemies.throwbo,
            enemies.spiderWolf,
            enemies.assassin,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.lurkerCrypt,
            enemies.throwbo,
            enemies.spiderWolf,
            enemies.assassin,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.fireWitch,
            enemies.cursedJar,
            enemies.gargoyleStatue,
            enemies.gargoyle,
            enemies.ticker,
            enemies.bat,
            enemies.necromancer,
            enemies.jumperWaterLarge,
            enemies.jumperOliLarge,
            enemies.skeletonEnemyNorm,
            enemies.skeletonEnemyCrimson,
            enemies.throwbo,
            enemies.lurkerCrypt,
            enemies.spiderWolf,
            enemies.assassin,
            enemies.trollBombardier,
            enemies.goblinTickerEngineer,
          ],
        },
      ],
    },
  ],
  [ //cavern
    {
      name:"cavern1",
      map:"cavern",
      zoneNumber: 4,
      startFloor: 16,
      baseDifficulty: 28,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,3,2],
      requirements: conditions.shadowlordNotKilled,
      floors: [
        {
          enemies: [
            enemies.jumperFireLarge,
            enemies.throwbo,
            enemies.assassin,
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.throwbo,
            enemies.assassin,
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.scaleTunnel,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.scaleTunnel,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.ogreAnnihilator,
            enemies.scaleTunnel,
            enemies.goblinTickerEngineer,
          ],
        },
      ],
    },
    {
      name:"cavern2",
      map:"cavern",
      zoneNumber: 4,
      startFloor: 16,
      baseDifficulty: 32,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,3,2],
      requirements: conditions.shadowlordKilled,
      floors: [
        {
          enemies: [
            enemies.assassin,
            enemies.throwbo,
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.scaleTunnel,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.assassin,
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.scaleTunnel,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.ogreAnnihilator,
            enemies.scaleTunnel,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.ogreAnnihilator,
            enemies.scaleTunnel,
            enemies.shaman02,
            enemies.goblinTickerEngineer,
          ],
        },
      ],
    },
    {
      name:"cavern3",
      map:"cavern",
      zoneNumber: 4,
      startFloor: 16,
      baseDifficulty: 36,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,3,2],
      requirements: conditions.crystallordKilled,
      floors: [
        {
          enemies: [
            enemies.assassin,
            enemies.throwbo,
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.ogreAnnihilator,
            enemies.scaleTunnel,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.ogreAnnihilator,
            enemies.scaleTunnel,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.ogreAnnihilator,
            enemies.scaleTunnel,
            enemies.shaman02,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.glimmerweed,
            enemies.trollBombardier,
            enemies.churchbell,
            enemies.lurkerCrystal,
            enemies.crystalAnt,
            enemies.crystalFly,
            enemies.crystalSpider,
            enemies.crystalWitch,
            enemies.ogreAnnihilator,
            enemies.scaleTunnel,
            enemies.shaman02,
            enemies.goblinTickerEngineer,
          ],
        },
      ],
    },
  ],
  [ //core
    {
      name:"core1",
      map:"core",
      zoneNumber: 5,
      startFloor: 21,
      baseDifficulty: 40,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,3,2],
      requirements: conditions.crystallordNotKilled,
      floors: [
        {
          enemies: [
            enemies.throwbo,
            enemies.assassin,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.crystalWitch,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.goblinTickerEngineer,
          ],
        },
        {
          enemies: [
            enemies.throwbo,
            enemies.assassin,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.crystalWitch,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
          ],
        },
        {
          enemies: [
            enemies.throwbo,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.crystalWitch,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.golem,
          ],
        },
        {
          enemies: [
            enemies.throwbo,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.golem,
          ],
        },
      ],
    },
    {
      name:"core2",
      map:"core",
      zoneNumber: 5,
      startFloor: 21,
      baseDifficulty: 44,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,3,2],
      requirements: conditions.crystallordKilledNotFire,
      floors: [
        {
          enemies: [
            enemies.throwbo,
            enemies.assassin,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.crystalWitch,
            enemies.ogreFirebomber,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
          ],
        },
        {
          enemies: [
            enemies.throwbo,
            enemies.assassin,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.golem,
          ],
        },
        {
          enemies: [
            enemies.throwbo,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.golem,
          ],
        },
        {
          enemies: [
            enemies.throwbo,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.golem,
          ],
        },
      ],
    },
    {
      name:"core3",
      map:"core",
      zoneNumber: 5,
      startFloor: 21,
      baseDifficulty: 48,
      difficultyStep: 2,
      enemyTypeWeight:[0,1,3,2],
      requirements: conditions.firelordKilled,
      floors: [
        {
          enemies: [
            enemies.throwbo,
            enemies.assassin,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.crystalWitch,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.golem,
          ],
        },
        {
          enemies: [
            enemies.throwbo,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.golem,
          ],
        },
        {
          enemies: [
            enemies.throwbo,
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.golem,
          ],
        },
        {
          enemies: [
            enemies.glimmerweed,
            enemies.lurkerCrystal,
            enemies.ogreFirebomber,
            enemies.magmaWormHead,
            enemies.firebat,
            enemies.shaman02,
            enemies.gremlin,
            enemies.gremlinFiery,
            enemies.flyRanged03,
            enemies.golem,
          ],
        },
      ],
    },
    {
      name:"bog",
      map:"bog",
      zoneNumber: 5,
      startFloor: 21,
      baseDifficulty: 50,
      difficultyStep: 6,
      enemyTypeWeight:[0,1,3,2],
      requirements: conditions.enterBog,
      floors: [
        {
          floorNumber: 21,
          enemies: [
            enemies.bingBong,
            enemies.flyBloat,
            enemies.quilledGolem,
            enemies.poisonWormHead,
            enemies.goblinPoisonEngineer,
            enemies.corruptedPilfer,
            enemies.shaman03,
            enemies.highPriest,
            enemies.queenFish,
          ],
        },
        {
          floorNumber: 22,
          enemies: [
            enemies.bingBong,
            enemies.flyBloat,
            enemies.quilledGolem,
            enemies.poisonWormHead,
            enemies.goblinPoisonEngineer,
            enemies.corruptedPilfer,
            enemies.shaman03,
            enemies.highPriest,
            enemies.queenFish,
          ],
        },
        {
          floorNumber: 23,
          enemies: [
            enemies.bingBong,
            enemies.flyBloat,
            enemies.quilledGolem,
            enemies.poisonWormHead,
            enemies.goblinPoisonEngineer,
            enemies.corruptedPilfer,
            enemies.shaman03,
            enemies.highPriest,
            enemies.queenFish,
          ],
        },
        {
          floorNumber: 24,
          enemies: [
            enemies.bingBong,
            enemies.flyBloat,
            enemies.quilledGolem,
            enemies.poisonWormHead,
            enemies.goblinPoisonEngineer,
            enemies.corruptedPilfer,
            enemies.shaman03,
            enemies.highPriest,
            enemies.queenFish,
          ],
        },
      ],
    },
  ],
]