const zoneData = [
  [ //mine
    {
      name:"mine1",
      map:"mineEarly",
      requirements: !(conditions.rockmimicDefeated),
      floors: [
        {
          floorNumber: 1,
          difficulty: 3,
          enemyTypeWeight:[0,1,2],
          enemies: [
            enemies.ratBasic,
            enemies.jumperWater,
            enemies.flyRanged,
          ],
        },
        {
          floorNumber: 2,
          difficulty: 5,
          enemyTypeWeight:[0,1,2],
          enemies: [
            enemies.ratBasic,
            enemies.jumperWater,
            enemies.flyRanged,
          ],
        },
        {
          floorNumber: 3,
          difficulty: 8,
          enemyTypeWeight:[0,1,2],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperWater,
            enemies.ratNest,
          ],
        },
        {
          floorNumber: 4,
          difficulty: 10,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.jumperWater,
            enemies.jumperOli,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
          ],
        },
      ],
    },
    {
      name:"mine2",
      map:"mine",
      requirements: !(conditions.sandwormDefeated),
      floors: [
        {
          floorNumber: 1,
          difficulty: 5,
          enemyTypeWeight:[0,1,2],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperWater,
            enemies.ratNest,
          ],
        },
        {
          floorNumber: 2,
          difficulty: 8,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.ratTough,
          ],
        },
        {
          floorNumber: 3,
          difficulty: 10,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
          ],
        },
        {
          floorNumber: 4,
          difficulty: 12,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
          ],
        },
      ],
    },
    {
      name:"mine3",
      map:"mine",
      requirements: !(conditions.stonelordDefeated),
      floors: [
        {
          floorNumber: 1,
          difficulty: 8,
          enemyTypeWeight:[0,1,2],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.ratTough,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          floorNumber: 2,
          difficulty: 10,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          floorNumber: 3,
          difficulty: 12,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          floorNumber: 4,
          difficulty: 12,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bat,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
      ],
    },
    {
      name:"mine4",
      map:"mine",
      requirements: !(conditions.shadowlordDefeated),
      floors: [
        {
          floorNumber: 1,
          difficulty: 12,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.ratTough,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          floorNumber: 2,
          difficulty: 14,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.ogreBombardier,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          floorNumber: 3,
          difficulty: 16,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          difficulty: 18,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bat,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
      ],
    },
    {
      name:"mine5",
      map:"mine",
      requirements: !(conditions.crystallordDefeated),
      floors: [
        {
          difficulty: 16,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.ratTough,
            enemies.bobo,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          floorNumber: 2,
          difficulty: 18,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratBasic,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          floorNumber: 3,
          difficulty: 20,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.ratNest,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bat,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          floorNumber: 4,
          difficulty: 22,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.ratLarge,
            enemies.flyRanged,
            enemies.jumperOli,
            enemies.jumperWater,
            enemies.lurkerBasic,
            enemies.ratTough,
            enemies.bobo,
            enemies.spiderBasic,
            enemies.bat,
            enemies.shaman,
            enemies.bugLightning,
            enemies.ogreBombardier,
            enemies.goblinEngineer,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
      ],
    },
  ],
  [ //dungeon
    {
      name:"dungeon1",
      map:"dungeon",
      requirements: !(conditions.rockmimicDefeated),
      floors: [
        {
          zoneNumber: 2,
          floorNumber: 6,
          difficulty: 12,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.ratTough,
            enemies.ratLarge,
            enemies.bat,
            enemies.spiderBasic,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 7,
          difficulty: 14,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.crossbowman,
            enemies.bishFish,
            enemies.rookFish,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 8,
          difficulty: 16,
          enemyTypeWeight:[0,0,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 9,
          difficulty: 18,
          enemyTypeWeight:[0,0,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
      ],
    },
    {
      name:"dungeon2",
      map:"dungeon",
      requirements: !(conditions.sandwormDefeated),
      floors: [
        {
          zoneNumber: 2,
          floorNumber: 6,
          difficulty: 16,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.crossbowman,
            enemies.bishFish,
            enemies.rookFish,
            enemies.goblinEngineer,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 7,
          difficulty: 18,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
            enemies.goblinEngineer,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 8,
          difficulty: 20,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 9,
          difficulty: 22,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
      ],
    },
    {
      name:"dungeon3",
      map:"dungeon",
      requirements: !(conditions.stonelordDefeated),
      floors: [
        {
          zoneNumber: 2,
          floorNumber: 6,
          difficulty: 20,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.crossbowman,
            enemies.goblinEngineer,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 7,
          difficulty: 22,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 8,
          difficulty: 24,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 9,
          difficulty: 26,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.crossbowman,
          ],
        },
      ],
    },
    {
      name:"dungeon4",
      map:"dungeon",
      requirements: !(conditions.shadowlordDefeated),
      floors: [
        {
          zoneNumber: 2,
          floorNumber: 6,
          difficulty: 24,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 7,
          difficulty: 26,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 8,
          difficulty: 28,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 9,
          difficulty: 30,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.skeletonEnemyNorm,
            enemies.gargoyle,
            enemies.gargoyleStatue,
            enemies.crossbowman,
          ],
        },
      ],
    },
    {
      name:"dungeon5",
      map:"dungeon",
      requirements: !(conditions.crystallordDefeated),
      floors: [
        {
          zoneNumber: 2,
          floorNumber: 6,
          difficulty: 28,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.jumperFire,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.flyRanged,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 7,
          difficulty: 30,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 8,
          difficulty: 32,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.crossbowman,
          ],
        },
        {
          zoneNumber: 2,
          floorNumber: 9,
          difficulty: 34,
          enemyTypeWeight:[0,1,2,1],
          enemies: [
            enemies.bugLightning,
            enemies.priest,
            enemies.ratTough,
            enemies.footman,
            enemies.ratLarge,
            enemies.bat,
            enemies.shaman,
            enemies.spiderBasic,
            enemies.fireWitch,
            enemies.flyRanged02,
            enemies.ticker,
            enemies.skeletonEnemyNorm,
            enemies.gargoyle,
            enemies.gargoyleStatue,
            enemies.crossbowman,
          ],
        },
      ],
    },
  ],
  [ //hall
    [
      {
        zoneNumber: 3,
        floorNumber: 11,
        difficulty: 20,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.skeletonEnemyNorm,
          enemies.lurkerCrypt,
          enemies.jumperWaterLarge,
          enemies.spiderWolf,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 12,
        difficulty: 22,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.skeletonEnemyNorm,
          enemies.lurkerCrypt,
          enemies.throwbo,
          enemies.spiderWolf,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 13,
        difficulty: 24,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.throwbo,
          enemies.lurkerCrypt,
          enemies.spiderWolf,
          enemies.assassin,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 14,
        difficulty: 24,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyle,
          enemies.gargoyleStatue,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.throwbo,
          enemies.lurkerCrypt,
          enemies.spiderWolf,
          enemies.assassin,
          enemies.goblinTickerEngineer,
        ],
      },
    ],
    [
      {
        zoneNumber: 3,
        floorNumber: 11,
        difficulty: 24,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.skeletonEnemyNorm,
          enemies.lurkerCrypt,
          enemies.jumperWaterLarge,
          enemies.spiderWolf,
          enemies.throwbo,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 12,
        difficulty: 26,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.lurkerCrypt,
          enemies.throwbo,
          enemies.spiderWolf,
          enemies.assassin,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 13,
        difficulty: 28,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.throwbo,
          enemies.lurkerCrypt,
          enemies.spiderWolf,
          enemies.assassin,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 14,
        difficulty: 30,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyle,
          enemies.gargoyleStatue,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.throwbo,
          enemies.lurkerCrypt,
          enemies.spiderWolf,
          enemies.assassin,
          enemies.goblinTickerEngineer,
        ],
      },
    ],
    [
      {
        zoneNumber: 3,
        floorNumber: 11,
        difficulty: 28,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.lurkerCrypt,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.spiderWolf,
          enemies.throwbo,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 12,
        difficulty: 30,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.lurkerCrypt,
          enemies.throwbo,
          enemies.spiderWolf,
          enemies.assassin,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 13,
        difficulty: 32,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.throwbo,
          enemies.lurkerCrypt,
          enemies.spiderWolf,
          enemies.assassin,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 14,
        difficulty: 34,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyle,
          enemies.gargoyleStatue,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.throwbo,
          enemies.lurkerCrypt,
          enemies.spiderWolf,
          enemies.assassin,
          enemies.goblinTickerEngineer,
        ],
      },
    ],
    [
      {
        zoneNumber: 3,
        floorNumber: 11,
        difficulty: 28,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.lurkerCrypt,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.spiderWolf,
          enemies.throwbo,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 12,
        difficulty: 30,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.lurkerCrypt,
          enemies.throwbo,
          enemies.spiderWolf,
          enemies.assassin,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 13,
        difficulty: 32,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.lurkerCrypt,
          enemies.throwbo,
          enemies.spiderWolf,
          enemies.assassin,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 3,
        floorNumber: 14,
        difficulty: 34,
        enemyTypeWeight:[0,1,2,1],
        enemies: [
          enemies.fireWitch,
          enemies.cursedJar,
          enemies.gargoyleStatue,
          enemies.gargoyle,
          enemies.ticker,
          enemies.bat,
          enemies.necromancer,
          enemies.jumperWaterLarge,
          enemies.jumperOliLarge,
          enemies.skeletonEnemyNorm,
          enemies.skeletonEnemyCrimson,
          enemies.throwbo,
          enemies.lurkerCrypt,
          enemies.spiderWolf,
          enemies.assassin,
          enemies.trollBombardier,
          enemies.goblinTickerEngineer,
        ],
      },
    ],
  ],
  [ //cavern
    [
      {
        zoneNumber: 4,
        floorNumber: 16,
        difficulty: 28,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.jumperFireLarge,
          enemies.throwbo,
          enemies.assassin,
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 4,
        floorNumber: 17,
        difficulty: 30,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.assassin,
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.scaleTunnel,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 4,
        floorNumber: 18,
        difficulty: 32,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.scaleTunnel,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 4,
        floorNumber: 19,
        difficulty: 34,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.ogreAnnihilator,
          enemies.scaleTunnel,
          enemies.goblinTickerEngineer,
        ],
      },
    ],
    [
      {
        zoneNumber: 4,
        floorNumber: 16,
        difficulty: 32,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.assassin,
          enemies.throwbo,
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.scaleTunnel,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 4,
        floorNumber: 17,
        difficulty: 34,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.assassin,
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.scaleTunnel,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 4,
        floorNumber: 18,
        difficulty: 36,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.ogreAnnihilator,
          enemies.scaleTunnel,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 4,
        floorNumber: 19,
        difficulty: 38,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.ogreAnnihilator,
          enemies.scaleTunnel,
          enemies.shaman02,
          enemies.goblinTickerEngineer,
        ],
      },
    ],
    [
      {
        zoneNumber: 4,
        floorNumber: 16,
        difficulty: 36,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.assassin,
          enemies.throwbo,
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.ogreAnnihilator,
          enemies.scaleTunnel,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 4,
        floorNumber: 17,
        difficulty: 38,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.ogreAnnihilator,
          enemies.scaleTunnel,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 4,
        floorNumber: 18,
        difficulty: 40,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.ogreAnnihilator,
          enemies.scaleTunnel,
          enemies.shaman02,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 4,
        floorNumber: 19,
        difficulty: 42,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.glimmerweed,
          enemies.trollBombardier,
          enemies.churchbell,
          enemies.lurkerCrystal,
          enemies.crystalAnt,
          enemies.crystalFly,
          enemies.crystalSpider,
          enemies.crystalWitch,
          enemies.ogreAnnihilator,
          enemies.scaleTunnel,
          enemies.shaman02,
          enemies.goblinTickerEngineer,
        ],
      },
    ],
  ],
  [ //core
    [
      {
        zoneNumber: 5,
        floorNumber: 21,
        difficulty: 40,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.assassin,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.crystalWitch,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.goblinTickerEngineer,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 22,
        difficulty: 42,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.assassin,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.crystalWitch,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 23,
        difficulty: 44,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.crystalWitch,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.golem,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 24,
        difficulty: 46,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.golem,
        ],
      },
    ],
    [
      {
        zoneNumber: 5,
        floorNumber: 21,
        difficulty: 44,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.assassin,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.crystalWitch,
          enemies.ogreFirebomber,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 22,
        difficulty: 46,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.assassin,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.golem,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 23,
        difficulty: 48,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.golem,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 24,
        difficulty: 50,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.golem,
        ],
      },
    ],
    [
      {
        zoneNumber: 5,
        floorNumber: 21,
        difficulty: 48,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.assassin,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.crystalWitch,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.golem,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 22,
        difficulty: 50,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.golem,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 23,
        difficulty: 52,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.throwbo,
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.golem,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 24,
        difficulty: 52,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.glimmerweed,
          enemies.lurkerCrystal,
          enemies.ogreFirebomber,
          enemies.magmaWormHead,
          enemies.firebat,
          enemies.shaman02,
          enemies.gremlin,
          enemies.gremlinFiery,
          enemies.flyRanged03,
          enemies.golem,
        ],
      },
    ],
  ],
  [ //bog
    [
      {
        zoneNumber: 5,
        floorNumber: 21,
        difficulty: 50,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.bingBong,
          enemies.flyBloat,
          enemies.quilledGolem,
          enemies.poisonWormHead,
          enemies.goblinPoisonEngineer,
          enemies.corruptedPilfer,
          enemies.shaman03,
          enemies.highPriest,
          enemies.queenFish,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 22,
        difficulty: 56,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.bingBong,
          enemies.flyBloat,
          enemies.quilledGolem,
          enemies.poisonWormHead,
          enemies.goblinPoisonEngineer,
          enemies.corruptedPilfer,
          enemies.shaman03,
          enemies.highPriest,
          enemies.queenFish,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 23,
        difficulty: 64,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.bingBong,
          enemies.flyBloat,
          enemies.quilledGolem,
          enemies.poisonWormHead,
          enemies.goblinPoisonEngineer,
          enemies.corruptedPilfer,
          enemies.shaman03,
          enemies.highPriest,
          enemies.queenFish,
        ],
      },
      {
        zoneNumber: 5,
        floorNumber: 24,
        difficulty: 70,
        enemyTypeWeight:[0,1,3,2],
        enemies: [
          enemies.bingBong,
          enemies.flyBloat,
          enemies.quilledGolem,
          enemies.poisonWormHead,
          enemies.goblinPoisonEngineer,
          enemies.corruptedPilfer,
          enemies.shaman03,
          enemies.highPriest,
          enemies.queenFish,
        ],
      },
    ],
  ]
]